### ISSUE TITLE
Make website more intuitive

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/website#35]
Student remark: People new to OpenML have difficulty finding what they need. With simple explanations (e.g. what is a task) and visual cues it should be possible to guide them in the right direction.

**Comment by jakobbossek** [comment]
I am not sure whether simple website/design changes are sufficient to address this issue.
IMHO this is not due to the complexity of the website, but due to the complexity of OpenML itself.
The latter cannot be reduced furhter IMHO.

Possible solutions:
- Maybe add screencast introduction to OpenML
- Add tooltips (see issue #64)
